server:
  port: 9000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://115.29.142.129:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order

#mybatis plus xml配置文件映射
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #自增组件
  global-config:
    db-config:
      id-type: auto